version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./backend/.env
    environment:
      MYSQL_DATABASE: ${DB_NAME:-monitor_portal_db}
      MYSQL_USER: ${DB_USER:-monitor_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-monitor_password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitor_network

  backend:
    build: ./backend
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "6300:8000"
    networks:
      - monitor_network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://backendmbinfrawatch.marketbytes.in
    restart: always
    depends_on:
      - backend
    ports:
      - "6301:80"
    networks:
      - monitor_network

networks:
  monitor_network:
    driver: bridge

volumes:
  mysql_data:
  static_volume:
  media_volume:
