# Generated by Django 6.0.2 on 2026-02-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SSH_FAIL', 'SSH Failed Login'), ('UFW_BLOCK', 'Firewall Block'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('raw_log', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
