# Generated by Django 6.0 on 2026-02-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(blank=True, choices=[('SSH_FAIL', 'SSH Failed Login'), ('UFW_BLOCK', 'Firewall Block'), ('OTHER', 'Other')], default='OTHER', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='is_resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='raw_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
