# Generated by Django 6.0.2 on 2026-03-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_securityevent_detected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(blank=True, choices=[('UFW_BLOCK', 'Firewall Block'), ('OTHER', 'Other')], default='OTHER', max_length=20, null=True),
        ),
    ]
