# Generated by Django 6.0.2 on 2026-02-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_type', models.CharField(choices=[('EMAIL', 'Email'), ('WEBHOOK', 'Webhook')], default='EMAIL', max_length=20)),
                ('value', models.CharField(help_text='Email address or Webhook URL', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='check_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='keyword',
            field=models.CharField(blank=True, help_text='Keyword to search for (Content Matching)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='monitor_type',
            field=models.CharField(choices=[('HTTP', 'HTTP(s)'), ('KEYWORD', 'Keyword'), ('PING', 'Ping'), ('PORT', 'Port')], default='HTTP', max_length=20),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='port',
            field=models.IntegerField(blank=True, help_text='Port for Port Monitoring', null=True),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='ssl_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='ssl_issuer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='timeout',
            field=models.IntegerField(default=30, help_text='Timeout in seconds'),
        ),
        migrations.AlterField(
            model_name='monitoredurl',
            name='url',
            field=models.CharField(help_text='URL or IP address', max_length=255),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='alert_contacts',
            field=models.ManyToManyField(blank=True, to='monitor.alertcontact'),
        ),
    ]
