# Generated by Django 6.0 on 2026-02-06 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alertcontact_monitoredurl_check_ssl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertcontact',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('WEBHOOK', 'Webhook')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alertcontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertcontact',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alertcontact',
            name='value',
            field=models.CharField(blank=True, help_text='Email address or Webhook URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredurl',
            name='interval',
            field=models.IntegerField(blank=True, default=5, help_text='Check interval in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='monitoredurl',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredurl',
            name='monitor_type',
            field=models.CharField(blank=True, choices=[('HTTP', 'HTTP(s)'), ('KEYWORD', 'Keyword'), ('PING', 'Ping'), ('PORT', 'Port')], default='HTTP', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredurl',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredurl',
            name='timeout',
            field=models.IntegerField(blank=True, default=30, help_text='Timeout in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='monitoredurl',
            name='url',
            field=models.CharField(blank=True, help_text='URL or IP address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uptimerecord',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='uptimerecord',
            name='is_up',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uptimerecord',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='monitor.monitoredurl'),
        ),
    ]
