# Generated by Django 6.0 on 2026-02-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_alertcontact_contact_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredurl',
            name='expected_status_code',
            field=models.IntegerField(blank=True, default=200, help_text='Wait for specific status code', null=True),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='http_method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='post_data',
            field=models.TextField(blank=True, help_text='JSON data for POST/PUT requests', null=True),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='request_headers',
            field=models.TextField(blank=True, help_text='JSON format headers', null=True),
        ),
        migrations.AlterField(
            model_name='alertcontact',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('WEBHOOK', 'Webhook'), ('SLACK', 'Slack'), ('DISCORD', 'Discord')], default='EMAIL', max_length=20, null=True),
        ),
    ]
