# Generated by Django 6.0.2 on 2026-02-10 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_monitoredurl_expected_status_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredurl',
            name='category',
            field=models.CharField(choices=[('SITES', 'Websites'), ('SSH', 'SSH')], default='SITES', max_length=10),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='check_domain_expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='check_ssl_errors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='check_ssl_expiry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='dns_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='domain_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='notify_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='team_members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='visible_on_status_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='monitoredurl',
            name='monitor_type',
            field=models.CharField(blank=True, choices=[('HTTP', 'HTTP(s)'), ('KEYWORD', 'Keyword'), ('PING', 'Ping'), ('PORT', 'Port'), ('CRON', 'Cron Job'), ('API', 'API Monitoring')], default='HTTP', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredurl',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Name'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('root_cause', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitor.monitoredurl')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('log_type', models.CharField(default='INFO', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='monitor.incident')),
            ],
        ),
    ]
