# Generated by Django 6.0.2 on 2026-02-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_maintenancewindow_statuspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredurl',
            name='monitor_cpu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='monitor_disk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='monitor_load',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='monitor_ram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='ssh_key',
            field=models.TextField(blank=True, help_text='private key for SSH access', null=True),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='ssh_port',
            field=models.IntegerField(blank=True, default=22, null=True),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='ssh_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uptimerecord',
            name='metrics',
            field=models.JSONField(blank=True, help_text='Store SSH metrics like CPU, RAM, etc.', null=True),
        ),
    ]
