# Generated by Django 6.0 on 2026-02-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_monitoredurl_monitor_cpu_monitoredurl_monitor_disk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredurl',
            name='monitor_cpu',
        ),
        migrations.RemoveField(
            model_name='monitoredurl',
            name='monitor_disk',
        ),
        migrations.RemoveField(
            model_name='monitoredurl',
            name='monitor_load',
        ),
        migrations.RemoveField(
            model_name='monitoredurl',
            name='monitor_ram',
        ),
        migrations.RemoveField(
            model_name='monitoredurl',
            name='ssh_port',
        ),
        migrations.RemoveField(
            model_name='uptimerecord',
            name='metrics',
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='ssh_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uptimerecord',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uptimerecord',
            name='disk_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uptimerecord',
            name='ram_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uptimerecord',
            name='system_uptime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredurl',
            name='monitor_type',
            field=models.CharField(blank=True, choices=[('HTTP', 'HTTP(s)'), ('KEYWORD', 'Keyword'), ('PING', 'Ping'), ('PORT', 'Port'), ('CRON', 'Cron Job'), ('API', 'API Monitoring'), ('SSH', 'SSH Monitoring')], default='HTTP', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredurl',
            name='ssh_key',
            field=models.TextField(blank=True, help_text='Private Key for SSH', null=True),
        ),
    ]
