# Generated by Django 6.0.2 on 2026-03-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_remove_monitoredurl_monitor_cpu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredurl',
            name='check_domain_expiry',
        ),
        migrations.RemoveField(
            model_name='monitoredurl',
            name='dns_monitoring',
        ),
        migrations.RemoveField(
            model_name='monitoredurl',
            name='domain_expiry',
        ),
        migrations.RemoveField(
            model_name='monitoredurl',
            name='notify_phone',
        ),
        migrations.RemoveField(
            model_name='monitoredurl',
            name='ssh_key',
        ),
        migrations.RemoveField(
            model_name='monitoredurl',
            name='ssh_password',
        ),
        migrations.RemoveField(
            model_name='monitoredurl',
            name='ssh_username',
        ),
        migrations.RemoveField(
            model_name='uptimerecord',
            name='cpu_usage',
        ),
        migrations.RemoveField(
            model_name='uptimerecord',
            name='disk_usage',
        ),
        migrations.RemoveField(
            model_name='uptimerecord',
            name='ram_usage',
        ),
        migrations.RemoveField(
            model_name='uptimerecord',
            name='system_uptime',
        ),
        migrations.AlterField(
            model_name='monitoredurl',
            name='category',
            field=models.CharField(choices=[('SITES', 'Websites')], default='SITES', max_length=10),
        ),
        migrations.AlterField(
            model_name='monitoredurl',
            name='monitor_type',
            field=models.CharField(blank=True, choices=[('HTTP', 'HTTP(s)'), ('KEYWORD', 'Keyword'), ('PING', 'Ping'), ('PORT', 'Port'), ('CRON', 'Cron Job'), ('API', 'API Monitoring')], default='HTTP', max_length=20, null=True),
        ),
    ]
