# Generated by Django 6.0.2 on 2026-03-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_remove_monitoredurl_check_domain_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredurl',
            name='monitor_type',
            field=models.CharField(blank=True, choices=[('HTTP', 'HTTP(s)'), ('KEYWORD', 'Keyword'), ('PING', 'Ping'), ('PORT', 'Port'), ('API', 'API Monitoring')], default='HTTP', max_length=20, null=True),
        ),
    ]
