# Generated by Django 6.0.2 on 2026-03-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_alter_monitoredurl_monitor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uptimerecord',
            name='is_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
